### ISSUE TITLE
Handling Metamask's lack of websocket support/Web3 1.0

### ISSUE THREAD

**Issue by sprice** [ConsenSys-archive/drizzle-legacy#10]
First of all. This looks super amazing! Thank you!

Using this with Metamask results in `Error: The current provider doesn't support subscriptions: MetamaskInpageProvider` [metamask-extension/2601](https://github.com/MetaMask/metamask-extension/issues/2601) & [metamask-extension/2350](https://github.com/MetaMask/metamask-extension/issues/2350)

Does this mean that the subscription parts of Drizzle can't be used with Metamask at the moment?

edit: Note I'm using the drizzle truffle box with Ganache

**Comment by andytudhope** [comment]
Same error as above for me 👍

**Comment by Coolpix** [comment]
Same for me!

**Comment by apanizo** [comment]
The same result using the same environment, but if I disable metamask... I get..

EDIT: That problem was caused because I did not have the latest (beta) version of **ganache-cli** (see my next comment).

![screenshot 2018-02-28 17 09 57](https://user-images.githubusercontent.com/4266059/36798225-52258764-1caa-11e8-8d2b-fb56436380f5.png)

Let me know if I should open a new issue or need something else.

And... congrats! The project looks amazing!

**Comment by apanizo** [comment]
Sorry! My bad, after reading [this](https://github.com/trufflesuite/ganache-cli/issues/257) and [this](https://github.com/trufflesuite/ganache-core/pull/49), I realised I just needed to update my **ganache-cli** version.

Thanks!

**Comment by sprice** [comment]
Ah. I'm using the Ganache App (1.0.2). I guess I need to switch over to the CLI and wait for the app to be updated. Thanks.

I'm going to test this out tonight to be sure and then likely close the issue.

**Comment by apanizo** [comment]
Oh sorry, I just tried to say the ws problem, which only happens if you disable Metamask, was solved after updating the ganache-cli to the beta version, but the error you reported, using Metamask, is still there. We have to wait until Metamask is updated. 

In other words, this issue makes sense 👍

**Comment by jaderiverstokes** [comment]
I'm working on an app using ws with drizzle to load data and metamask to process the transactions.  So it is possible, although it's quite messy.

**Comment by elie222** [comment]
So seems like Drizzle is mostly unusable right now as MetaMask is the main way to interact with Dapps?

**Comment by elie222** [comment]
Would it be possible to use Infura for websockets and MetaMask for everything else?

I see Infura recently added WS support:
https://github.com/INFURA/infura/issues/29

**Comment by davekay100** [comment]
@elie222 yes, i have done that as a solution. you need to keep track of two different web3 instance. it is a hacky solution that works for now

**Comment by elie222** [comment]
Would be nice if you could post what you did as an example.

The web3 instance you pass to Drizzle is the infura one I take it? And then
separately you do txs with metamask? Doesn't Drizzle also expect txs to be
done through it too though?

**Comment by keithpops** [comment]
@cooper-sloan && @davekaj I'm very interested in seeing what methods you've come up with in managing multiple web3 instances to use drizzle with MetaMask. I've also been investigating this and would love to see what other solutions people have come up.

**Comment by arjunyel** [comment]
If anyone could write up a quick tutorial on the workaround for using Drizzle with metamask that would be a HUGE help to the community :)

**Comment by davekay100** [comment]
damn, sorry was not paying enough attention, i have not done this with drizzle. i only did it with a normal react project

**Comment by balasan** [comment]
I got it working with Metamask — using infura rpc for websocket updates and metamask for accounts and transactions: https://github.com/relevant-community/drizzle/blob/master/src/Drizzle.js

It's building on PR #15 but also storing the Metamask instance of web3 and using it for drizzle contract calls.

*Beware* my fork has some braking changes in the ```accounts``` reducer - list of accounts is now stored in ```ids``` field to accommodate and additional ```balances``` field.

**Comment by DiscRisknBisque** [comment]
Right off the bat I've got to apologize for not hopping in this conversation earlier!

Today, Drizzle supports MetaMask via a fallback to their very own [`eth-block-tracker`](https://github.com/MetaMask/eth-block-tracker) package (see [release v1.1.4](https://github.com/trufflesuite/drizzle/releases/tag/1.1.4)). Release notes for v1.1 are also relevant as it was the first time MetaMask support rolled out.

Hope you'll all give it another shot if you haven't already. 🙂
