### ISSUE TITLE
Missing `default` keyword

### ISSUE THREAD

**Issue by tearsofphoenix** [ConsenSys-archive/drizzle-legacy#102]
It should has a `default` keyword after `export`!
https://github.com/trufflesuite/drizzle/blob/f80781ccdee0d01cc238cc5b3475437844be2614/src/index.js#L41

**Comment by soundyogi** [comment]
Not in every case.
Named exports have advantages (for example people cant just give it any name when importing)

It is a design choice really.

I think this issue can be closed :)
