### ISSUE TITLE
Contract events array not being populated

### ISSUE THREAD

**Issue by BryceMindLab** [ConsenSys-archive/drizzle-legacy#108]
```drizzle v1.2.2```
```node v8.11.3```

I would like to use drizzle to monitor events happening from my smart contract. Reading the docs I setup ```drizzleOptions.js``` with an array of strings that correspond to the contract's events, but when checking the state there are no events populated in the contract's event array. 

```
// drizzleOptions.js
import SomeToken from '../../build/contracts/SomeToken.json'

const drizzleOptions = {
  web3: {
    block: false,
    fallback: {
      type: 'ws',
      url: 'ws://127.0.0.1:8545'
    }
  },
  contracts: [
    SomeToken
  ],
  events: {
    'SomeToken': [
      'Approval',
      'Transfer',
      'Purchased',
    ]
  },
  polls: {
    accounts: 1500
  }
}

export default drizzleOptions
```

Here is the state tree (```events``` array being a child of ```SomeToken``` contract):
![screen shot 2018-08-02 at 2 02 26 pm](https://user-images.githubusercontent.com/2391536/43605026-ccdc9a8e-965c-11e8-9c73-30a2f6a0f08d.png)

**Comment by BryceMindLab** [comment]
After some digging, I found this string of operations being performed during the initialization phase of drizzle. 

In ```contractsReducer.js``` each contract is generated with the ```generateContractInitialState()``` function as seen below.  In this function only the objects with ```type === function``` are added to the state. This seems fairly normal because we needed to add events to monitor in ```drizzleOptions.js```.  

What seems like an issue to me is that once the contract is initialized the events in the contract are set to an empty array. __(Maybe we should be passing the events from ```drizzleOptions``` here to populate the events array?)__
```javascript
  if (action.type === 'CONTRACT_INITIALIZING') {
    return {
      ...state,
      [action.contractConfig.contractName]: generateContractInitialState(action.contractConfig)
    }
  }

  if (action.type === 'CONTRACT_INITIALIZED')
  {
    return {
      ...state,
      [action.name]: {
        ...state[action.name],
        initialized: true,
        synced: true,
        events: []
      }
    }
  }
```
[drizzle/src/contracts/contractsReducer.js](https://github.com/trufflesuite/drizzle/blob/09894441a9bd6be1ec24d6e9af83044a56204b44/src/contracts/contractsReducer.js) 


(As stated above, the initial contract state is created with only functions from the ABI, no events. Because we need to provide events in ```dirzzleOptions``` this would appear to be normal behavior) 
```javascript
import getAbi from './getAbi'

export function generateContractInitialState (contractConfig) {
  var state = {
    initialized: false,
    synced: false
  }

  // Constant getters
  var abi = getAbi(contractConfig)
  for (var i2 = 0; i2 < abi.length; i2++) {
    var item = abi[i2];

    if (item.type == "function" && item.constant === true) {
      state[item.name] = {}
    }
  }

  return state
```
[drizzle/src/generateContractInitialState.js](https://github.com/trufflesuite/drizzle/blob/09894441a9bd6be1ec24d6e9af83044a56204b44/src/generateContractInitialState.js)

In ```contractsSaga.js```, an ```eventListener``` is created for each event passed into ```drizzleOptions```, but it __seems to be monitoring ```contract.events```, which as shown above is initialized to an empty array.__ Could this be the reason why these events are not firing? 
```javascript
function createContractEventChannel({contract, eventName, eventOptions}) {
  const name = contract.contractName

  return eventChannel(emit => {
    const eventListener = contract.events[eventName](eventOptions).on('data', event => {
      emit({type: 'EVENT_FIRED', name, event})
    })
    .on('changed', event => {
      emit({type: 'EVENT_CHANGED', name, event})
    })
    .on('error', error => {
      emit({type: 'EVENT_ERROR', name, error})
      emit(END)
    })

    const unsubscribe = () => {
      eventListener.removeListener(eventName)
    }

    return unsubscribe
  })
}
```
[drizzle/src/contracts/contractsSaga.js](https://github.com/trufflesuite/drizzle/blob/c53e7116f9806e411a0834755172921d245efcde/src/contracts/contractsSaga.js)

**Comment by reime005** [comment]
I ran into the issue that nothing about events was printed to the console. But obviously there must have been an error. Fixed it with that code: https://github.com/reime005/drizzle/commit/a449f163851886e9e582d3075ba4631751c52b04

**Comment by johnmpotter** [comment]
For some reason, events aren't working for me either. I logged the error message, similar @reime005's suggestions and received this error:

`Error: The current provider doesn't support subscriptions: MetamaskInpageProvider`

It may be related to an issue with MetaMask not supporting web3 1.0 yet https://github.com/MetaMask/metamask-extension/issues/3642

According to #10, Drizzle has a work around for this, but i'm not sure if it applies to events.

**Comment by pors** [comment]
@DiscRiskandBisque can you confirm that the #10 fix indeed doesn't cover events? I also get the "not supported" error (after exposing it manually):

![screen shot 2018-10-05 at 10 09 03 am](https://user-images.githubusercontent.com/1078320/46521024-d769ad00-c886-11e8-9baa-0006b5b90600.png)

**Comment by pors** [comment]
BTW this might be a workaround until MetaMask supports web3 1.0 subscriptions: https://github.com/upperwal/web3-event-compatibility

**Comment by nahuely** [comment]
Hi there, im having the same issue, i would like to know if there is any progress on it? thanks so much

**Comment by pors** [comment]
Good news from MetaMask, subscription support is underway: https://github.com/MetaMask/metamask-extension/pull/5458

**Comment by nahuely** [comment]
update to the latest metamask version, the event array its getting populated, and the websockets provider its working, im so so happy thanks

**Comment by BryceMindLab** [comment]
Thanks for the update!
