### ISSUE TITLE
Can't easily integrate into an existing application that uses Redux?

### ISSUE THREAD

**Issue by jvventura** [ConsenSys-archive/drizzle-legacy#11]
Firstly, thanks for starting this project! Very serendipitous as I was able to start writing a state manager for my React+Redux app for managing web3 and contract calls.

Onto the serious stuff. Redux best practices (according to their repo) says that you should only have one store for your app. If my Redux store is already instantiated with createStore(), I do not believe there is a way to easily merge the Drizzle instantiated store with my existing Redux store. Correct me if I'm wrong!

What is the best way that Drizzle can integrate into existing React+Redux dApps?

P.S. I am happy to contribute to the repo if you can point me on the right direction on the best way to implement easy integration into existing Redux stores.

**Comment by claykohut** [comment]
I'm interested in the same thing

**Comment by tothemoonguru** [comment]
The interface is very limited. Exporting middlewares, reducers & sagas would allow integrating this into existing stores easily.

**Comment by DiscRisknBisque** [comment]
@jvventura @claykohut @tothemoonguru Apologies I should have responded to this sooner! As of version 1.1, `drizzle` does now export its reducers and sagas. Read up more in our docs here: [Using an Existing Redux Store](http://truffleframework.com/docs/drizzle/using-an-existing-redux-store).
