### ISSUE TITLE
Drizzle initialization may fire too late

### ISSUE THREAD

**Issue by reime005** [ConsenSys-archive/drizzle-legacy#110]
I ran into the issue that the Drizzle action 'DRIZZLE_INITIALIZING' has not been fired, because the page was already loaded. Also, trying to access window may cause problems when for example using a library site generator / SSR.

https://github.com/trufflesuite/drizzle/blob/def2ad6c6ad28e64fb52f76a82c919dc06c6287f/src/Drizzle.js#L3

**Comment by robertdavid010** [comment]
Not sure if appropriate for this issue, but it's related to the same line of code...

This is not a common use case, but occassionally it may be advantageous to have the Redux store available on a NodeJS server. As an example: [Redux Server Side in NodeJS](https://www.quora.com/Can-Redux-be-used-for-server-side-Node-js-without-any-UI).

By conditionally attaching the Promise to either the client `window` or some server `global` depending on the context, this should make Drizzle work on the server?

**Comment by adrianmcli** [comment]
@reime005 I think I understand where you are coming from. Maybe something like [this](https://github.com/adrianmcli/truffle-next/blob/master/client/lib/getWeb3.js#L20-L30) (from my personal Truffle box) might solve it?

```js
export default () =>
  new Promise((resolve) => {
    // Wait for loading completion to avoid race conditions with web3 injection timing.
    window.addEventListener(`load`, () => {
      resolveWeb3(resolve)
    })
    // If document has loaded already, try to get Web3 immediately.
    if (document.readyState === `complete`) {
      resolveWeb3(resolve)
    }
  })
```

**Comment by adrianmcli** [comment]
In terms of using Drizzle on SSR and avoiding `document` or `window`, I can see how that could be a concern, but I just think that we simply can't support that use-case at the moment. You shouldn't really be loading Web3 and everything on the server-side (since we use the provider in the client).

**Comment by soundyogi** [comment]
Hiya,
I rewrote @adrianmcli exellent web3resolver to work with the new web3 ethereum provider and the ethereum.enable() method.

https://gist.github.com/soundyogi/cc049c3fe8bb045510e5925e2de196c9

**Comment by adrianmcli** [comment]
@soundyogi feel free to make a PR to fix this!

**Comment by soundyogi** [comment]
https://github.com/trufflesuite/drizzle/pull/139

This should do it. I was lazy so I went with the master branch.
I can do the whole 'develop-branch' thing with a branch for the changes tomorrow though if you wish, like a _proper_ contributor.

(Sorry its late today and of course I did forget to read the contributing.md at first, argh ^^; )

**Comment by adrianmcli** [comment]
@soundyogi, it looks good to me. It looks like the `develop` branch is stale anyways. No worries and thanks for doing this.

**Comment by soundyogi** [comment]
No thank YOU for doing this. Ill try to kill some more issues the next weeks when we have used drizzle a bit more. <3
