### ISSUE TITLE
Can I Use Redux-Thunk With DrizzleSagas?

### ISSUE THREAD

**Issue by hackingbeauty** [ConsenSys-archive/drizzle-legacy#121]
My React app uses Redux-Thunk; however, I want to incorporate drizzleSagas from the "drizzle" NPM package into my Dapp.

Do I have to convert my entire app to use Redux-Saga, or can I still use drizzleSagas with the rest of my app that uses Redux-Thunk?

**Comment by dangell7** [comment]
I used both...

**Comment by barlock** [comment]
You can use both thunks and sagas in the same redux store. Thunks act as a middleware and "interrupt" the process of the action where sagas "observe" what happens and perform side effects "off the main thread" (it doesn't actually, but I find it easier to think of it that way).

The only reason you might want to pick one or the other is for code consistency. If you're trying to integrate drizzle into an existing thunk-based project, you can just add the new middleware and `run` it without any changes to your existing code.

**Comment by soundyogi** [comment]
Both are completely seperate middleware. No Problem.

I usually use redux-thunk until my app get too large or I need to listen to a specific action.

This Issue can be closed :)

**Comment by hackingbeauty** [comment]
Thank you :)
