### ISSUE TITLE
Usage of pify breaks reference to provider

### ISSUE THREAD

**Issue by danfinlay** [ConsenSys-archive/drizzle-legacy#124]
At MetaMask we've been blocked from rolling out our new provider, because it breaks Drizzle, and we don't want to break every Drizzle app.

As documented in https://github.com/MetaMask/metamask-extension/issues/5459:

- Drizzle pifies its provider, breaking the `this` reference.
  - Should make sure `pify` method receives correct context argument.
  - May also require patch in blocktracker-es5 2.3.2, which we don't own. (I'm not clear what this would be yet, will define later).

**Comment by DiscRisknBisque** [comment]
Thanks for bringing this to our attention @danfinlay. Closing with merger of #131.
