### ISSUE TITLE
Is this compatible with Metamask yet? 

### ISSUE THREAD

**Issue by elie222** [ConsenSys-archive/drizzle-legacy#125]
From what I remember this package had a lot of issues with Metamask. As that's the go to wallet for most dapp users I didn't use this for any of my projects. Has this situation changed at all in the past few months?

**Comment by adrianmcli** [comment]
@elie222 can you elaborate on how it doesn't work with MetaMask?

**Comment by elie222** [comment]
When this was released there were issues with subscriptions and metamask
web3 1.0 support. It's been half a year now and metamask has made updates,
so was wondering if Drizzle now works properly with it.

**Comment by pors** [comment]
@elie222 Subscription support was an issue of MetaMask.  As of MetaMask 4.16+ subscriptions (and events) now work with drizzle.
