### ISSUE TITLE
Transaction object doesnt get updated

### ISSUE THREAD

**Issue by nahuely** [ConsenSys-archive/drizzle-legacy#127]
After using cacheSend to make a transaction, the transaction hash gets added to transaction object, but it doesnt move from pending state(but it was confirmed in the etherer explorer), if you need more information i would be glad to provide it, im using the latest version of drizzle and react-drizzle, also the latest version of metamask, cheers.

**Comment by mstobie-seequent** [comment]
This occurs as of metamask 4.14 and is a duplicate of #126

**Comment by soundyogi** [comment]
This Issue can be closed now.

**Comment by DiscRisknBisque** [comment]
Closing because this is fixed by #131.
