### ISSUE TITLE
Passing multiple variables to method via sendCache

### ISSUE THREAD

**Issue by chrisphua** [ConsenSys-archive/drizzle-legacy#128]
I finished the tutorial on 'GETTING STARTED WITH DRIZZLE AND REACT'. However, I realized on the part where 

```
setValue = value => {
    const { drizzle, drizzleState } = this.props;
    const contract = drizzle.contracts.MyStringStore;

    // let drizzle know we want to call the `set` method with `value`
    const stackId = contract.methods["set"].cacheSend(value, {        //HERE
      from: drizzleState.accounts[0]
    });
```
, that it could only send one variable. How do I send multiples variables to a method?

Update No.1:
I read the readme doc mentioning the **Drizzle State** has a key pair which is 'args' that pass to the function call. Is there anyone know how to use this?

Thanks in advance!

**Comment by oldwolf** [comment]
You can send the multiple values like this
```
const stackId = contract.methods["set"].cacheSend(value1, value2, value3, {        //HERE
    from: drizzleState.accounts[0]
});
```

**Comment by chrisphua** [comment]
@oldwolf Thanks! It works now.
