### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by barlock** [ConsenSys-archive/drizzle-legacy#130]
Supporting React Native would be quite helpful. There are a few things that's needed to make everything happy.

1. Initialization assumes a `window.addEventListener` which doesn't exist in RN (see #100)

2. Shims need to be in place for node/browser dependencies that don't exist in RN. Probably this should just be documented.

	**At the top of your entry point**
	```js
	// App.js or index.js
	
	import 'node-libs-react-native/globals';
	import { URL, URLSearchParams } from 'whatwg-url';
	import { btoa } from 'Base64';
	
	global.URL = URL;
	global.URLSearchParams = URLSearchParams;
	global.btoa = btoa;
	```
	
	**Configuration passed to react native cli**
	
	```js
	// rn-cli.config.js (>0.57)
	
	module.exports = {
	  resolver: {
	    extraNodeModules: require('node-libs-react-native')
	  }
	};
	```

3. The Webpack distribution is somehow incompatible outside of a browser 🤷‍♀️. Including the `src` directory and adding `"react-native": "src/index.js",` allows the metro bundler to compile it itself and it seems to be happy. 

	**Current Workaround**
    Add drizzle as a git dependency 
 😢 `git+https://github.com/trufflesuite/drizzle.git#1.2.3` and add a post-install script to inject the prop to allow metro to find the correct files

	<details>
	  <summary>Post install script</summary>
	
  	  ```js
	  const fs = require('fs-extra');
	  const drizzlePackage = require('../node_modules/drizzle/package.json');
	
	  (async () => {
	    // https://github.com/trufflesuite/drizzle/issues/130
	    drizzlePackage['react-native'] = './src/index.js';
	
	    await fs.writeFile(
	      './node_modules/drizzle/package.json',
	      JSON.stringify(drizzlePackage, null, 2)
	    );
	  })().catch(console.log);
	  ```
	</details>

	<details>
	  <summary>Current Unhelpful error for those interested</summary>
	  
	  ```log
	    console.error: "Unhandled promise rejection", {"line":98217,"column":34,"sourceURL":"http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false"}
	
		error
		    YellowBox.js:59:8
		<unknown>
		    drizzle.js:2583:24
		exports
		    drizzle.js:1826:30
		<unknown>
		    drizzle.js:2577:23
		_callTimer
		    JSTimers.js:152:14
		_callImmediatesPass
		    JSTimers.js:200:17
		callImmediates
		    JSTimers.js:464:30
		__callImmediates
		    MessageQueue.js:320:6
		<unknown>
		    MessageQueue.js:135:6
		__guard
		    MessageQueue.js:297:10
		flushedQueue
		    MessageQueue.js:134:17
	  ```
	</details>

**Comment by barlock** [comment]
@adrianmcli I don't see any code to roll releases so I can't seem to fix 3 which is the most annoying of the bunch. I'm assuming you're rolling these by hand? Could you include the source in the output? 

Is this attached to any CI? I could also make a pr to roll the release when one is made on github.

**Comment by barlock** [comment]
@DiscRiskandBisque ☝️ You seem to have rolled the release for drizzle before? (https://github.com/trufflesuite/drizzle/pull/56#issuecomment-392837190) 

Any thoughts on how we can include either the src or a react-native specific build?

**Comment by soundyogi** [comment]
Point 1. could probably easy fixed as commented here:
https://github.com/trufflesuite/drizzle/pull/100

Maybe we can put the complete discussion here.

Point 3. is a PITA Indeed.

**Comment by barlock** [comment]
Any idea how releases are created? It looks manual to me from @DiscRiskandBisque's account.

I see truffle is using Travis, I'll make a guess at how the release is built and make a pr. Someone would need to add env variables though. Any insight would be helpful.

**Comment by soundyogi** [comment]
Still pretty new here.
Maybe @adrianmcli or @DiscRiskandBisque could shed some light on the matter?

How are drizzle releases rolled out?

**Comment by adrianmcli** [comment]
Hmm, can point 3 be addressed by what @yvon did here? https://github.com/yvon/drizzle/commit/eb690e58161893dcbfc24f4baa08236585b4247b

It was talked about in this issue: https://github.com/trufflesuite/drizzle/issues/104

**Comment by barlock** [comment]
I don't think so, window is defined in react native, but sadly I've removed drizzle from my code base to easily test as I didn't have a web3 provider that supported subscriptions. I need to open an issue with uPort for that...

The reason I'm not sure is that by removing the compiled webpacked version, everything worked. The "standard" thing to do with React Native projects is to compile the source for node modules. I think that has to do with the fact that it uses it's own bundler (metro instead of webpack).

**Comment by adrianmcli** [comment]
@barlock Thanks for the input.
@soundyogi What's your opinion on #100?

**Comment by soundyogi** [comment]
https://github.com/trufflesuite/drizzle/pull/141

I generalized a bit since we maybe need more 'immediatly resolve' environments in the future (node?)
or other special stuff that has to be done for different environments.

This should work I hope, can someone test it?
I cant test it for RN at the moment.

**Comment by barlock** [comment]
Running to the end of a release, I'll make a test project in a few days.

**Comment by adrianmcli** [comment]
@barlock just did another read-through of this issue. Just to confirm what you are saying:

1. Make sure to try initialization right-away (i.e. not only depend on `window.addEventListener`)
2. Add the shims you mentioned in your first post
3. Publish the package w/ the `src` folder included
4. Add `"react-native": "src/index.js"` into the `package.json`

This would be sufficient for RN support right?

**Comment by soundyogi** [comment]
I need react-native for my next projects so I hope I can test this soon-ish.

**Comment by adrianmcli** [comment]
@soundyogi don't worry, we just got a new hire (@honestbonsai). He's working full-time on this right now, it's his top priority :)

**Comment by honestbonsai** [comment]
https://github.com/honestbonsai/reactNativeDrizzle test repo here. Note that the repo points to a branch of Drizzle (https://github.com/trufflesuite/drizzle/tree/feature/react-native) where the `window` issues during init should be taken care of. 

And just fyi had some issues with Drizzle 1.2.3, so the branch was off of `master` (commit 3933ed3c0c255c424324aba09b86239eb6ed7261). Basically needed this fix 38d815faeb36d52466e1ec36b66f4245ee8709c6.

Still working on some things with it, but could be a starting point for others as well.

I can get all the way to 
```
Error intializing web3:
12-10 19:11:17.054  6908  6938 E ReactNativeJS: { [Error: Creating URL objects is not supported yet.]
```

Which then leads to the fix of https://github.com/facebook/react-native/issues/16434 (and also mentioned above https://github.com/trufflesuite/drizzle/issues/130#issue-371252960)
```
import { URL, URLSearchParams } from 'whatwg-url';

global.URL = URL;
global.URLSearchParams = URLSearchParams;
```

But then I'm getting
```
Unexpected token '.' (http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:3486)

Unexpected token '.' (http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:3486)
```

**Comment by soundyogi** [comment]
Nice! We are getting close to this.

Initialization looks fine I can close #141 ! 

I could dig this up regarding the ```Unexpected token```, could be related at least:
https://github.com/ds300/react-native-typescript-transformer/issues/60

Looks like `'whatwg-url'` package does not work with node so it does not work with react-native js runtime aswell. My best guess atm.

**Comment by adrianmcli** [comment]
@honestbonsai note that v1.2.3 is pretty old. There are newer versions, as well as `@next` and `@pure`.

Go to https://www.npmjs.com/package/drizzle and click "versions".

**Comment by hyperh** [comment]
@soundyogi Yea going to look into alternatives for `whatwg-url`.

@adrianmcli Thanks for the heads up. I branched off `master` for now, but will check out those alternatives in the future.

**Comment by soundyogi** [comment]
^ that sounds pretty good actually.  less dependencies also.

**Comment by hyperh** [comment]
Ok so that worked pretty nicely https://github.com/trufflesuite/drizzle/issues/130#issuecomment-446288718. 

However there's an issue with the usage of `Object.assign` on RN (only on dev builds though, I tried out a production build and seems to work ok)

1. https://github.com/aframevr/aframe/issues/2375 (originally found out from here, following links come from this one)
1. https://github.com/facebook/react-native/issues/3634
1. https://github.com/facebook/metro/commit/9773229227895bfc5a5bde969108a4cbcc270eab#diff-ce1179d24387784c3c5f856c4b5b55d8R59

**Comment by honestbonsai** [comment]
Ok so that worked pretty nicely https://github.com/trufflesuite/drizzle/issues/130#issuecomment-446288718. 

However there's an issue with the usage of `Object.assign` on RN (only on dev builds though, I tried out a production build and seems to work ok)

1. https://github.com/aframevr/aframe/issues/2375 (originally found out from here, following links come from this one)
1. https://github.com/facebook/react-native/issues/3634
1. https://github.com/facebook/metro/commit/9773229227895bfc5a5bde969108a4cbcc270eab#diff-ce1179d24387784c3c5f856c4b5b55d8R59

**Comment by honestbonsai** [comment]
edit: Consolidating my previous comments under my member account

> 
> @soundyogi Yea going to look into alternatives for `whatwg-url`. It targets `jsdom` so guess I shouldn't be surprised that it doesn't work on node.
> 
> One of the issues is that `web3` goes down this path: https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers-ws/src/index.js#L37
> 
> `window` is defined on RN (points to `global`) and I guess `window.WebSocket` must be too, so it goes down that path which is why we have to shim `URL` with something that will work for that case, opening a PR for web3 would take a lot longer to get in, but could also be done in the future.
> 
> Thanks for the lead on the `Unexpected token` issue, will look more into it.
> 
> @adrianmcli Thanks for the heads up. I branched off `master` for now, but will check out those alternatives in the future.


> Haven't tried this yet, but off the top of my head, in order to replace whatwg-url, could just make our own URL class and use node's url.parse in its constructor (looking at the web3 alternative path).
> 
> Will try it today.


Ok so replacing `whatwg-url` worked pretty nicely

However there's an issue with the usage of `Object.assign` on RN (only on dev builds though, I tried out a production build and seems to work ok)

1. https://github.com/aframevr/aframe/issues/2375 (originally found out from here, following links come from this one)
1. https://github.com/facebook/react-native/issues/3634
1. https://github.com/facebook/metro/commit/9773229227895bfc5a5bde969108a4cbcc270eab#diff-ce1179d24387784c3c5f856c4b5b55d8R59 (this is why it fails on dev builds)

Perhaps `Object.assign` could be shimmed for RN builds only?

**Comment by soundyogi** [comment]
The `Object.assign`  is a userland thing thoug no? I mean the config for the bundler that bundles the RN app. So its not up to drizzle to fix that. Or we just use a custom `Obect.assign` for both and overwrite the method. Just a Thought.

**Comment by honestbonsai** [comment]
@soundyogi @barlock  I've just pushed up a fix for the `Object.assign` issue to the test repo https://github.com/honestbonsai/reactNativeDrizzle, check it out and let me know your thoughts. 

It's a rough working implementation. Right now got all the way up to Drizzle contract initialization (i.e. the test app doesn't crash immediately on load). Still need to test out Drizzle's functionality with calls and sends on contracts.

I'll be doing some more testing, cleaning up the implementation to make it more user friendly, and adding some docs/tutorial around the parts that Drizzle will not/cannot abstract away.

**Comment by honestbonsai** [comment]
Success! I've now replicated the [basic Drizzle tutorial](https://www.truffleframework.com/tutorials/getting-started-with-drizzle-and-react) in React Native. 

It's up in the test repo: https://github.com/honestbonsai/reactNativeDrizzle

**Comment by soundyogi** [comment]
Will test as soon as I can! Awesome!

**Comment by honestbonsai** [comment]
Added a couple more example tests to the test repo.

**Comment by honestbonsai** [comment]
#154 merged, but `/src` still needs to be published with the next release for this issue to be resolved

**Comment by youngkidwarrior** [comment]
a

**Comment by youngkidwarrior** [comment]
So with this change, how are we mapping state to props in our RN components. I'm coming from the perspective that hooks aren't implemented in React Native at the moment. Will we just use the old drizzle Provider?

**Comment by adrianmcli** [comment]
@youngkidwarrior that would be my understanding. No need to rush into hooks atm, IMO.

**Comment by youngkidwarrior** [comment]
Thanks. I ended up moving away from using a redux store but I had had it working.

**Comment by adrianmcli** [comment]
@youngkidwarrior That's awesome, not a big fan of redux myself. Do consider using https://github.com/trufflesuite/drizzle-utils
