### ISSUE TITLE
EIP1102 / Metamask breaking change compatibility

### ISSUE THREAD

**Issue by yosriady** [ConsenSys-archive/drizzle-legacy#135]
> In order to better protect user privacy, MetaMask and other dapp browsers will stop populating the injected Ethereum provider with user accounts by default. Instead, dapps must request access to user accounts, which will in turn ask the user to approve or deny access to the Ethereum blockchain. If the user approves access, the provider will be populated with accounts and the dapp can initiate account-requiring transactions as they normally would.
>
> https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

Is Drizzle compatible with this change? How would requiring user approval before exposing user accounts affect the overall flow?

**Comment by adrianmcli** [comment]
Yes, we are compatible, take a look at #131.

For now, we request access to accounts when we retrieve the provider. Will probably need a more flexible approach going forward.
