### ISSUE TITLE
Better error message for when Drizzle cannot find contract on the network

### ISSUE THREAD

**Issue by adrianmcli** [ConsenSys-archive/drizzle-legacy#136]
The `uncaught at root at root` error message is terrible; a simple search under this repo reveals many people who ran into this just because they are on the wrong network (often because they are using MetaMask set to mainnet) or simply because they forgot to deploy the contract.

The error really should be something like "The specified contract cannot be found on the specified network." or similar.

**Comment by joshma91** [comment]
@adrianmcli The fix in #138 doesn't get rid of the crappy `uncaught at root at root`, because that's required to show the stack trace. However, it shows a more descriptive message (the one you suggested) above it.

**Comment by adrianmcli** [comment]
@joshma91 do you think you can give a screenshot to show the before/after effect?

**Comment by joshma91** [comment]
Sure @adrianmcli, here's the before and after. If you don't like the after, I've also shown an option where we use `throw new Error('custom error msg')`

![image](https://user-images.githubusercontent.com/9612111/47573630-a19e6e00-d8f2-11e8-85d4-e48c3ffdf810.png)
