### ISSUE TITLE
BigNumber issue when converting fromWei()

### ISSUE THREAD

**Issue by rrubo** [ConsenSys-archive/drizzle-legacy#14]
Drizzle is massive, thanks a bunch! But can't pass an issue with BigNumbers. Not having seen info on Drizzle issues, have to post this here:

`value = <ContractData contract="Market" method="priceOf" methodArgs={this.props.id}/> `- returns a BigNumber object in Wei.

`web3.fromWei(value, 'ether')` gives an error `new BigNumber() not a number: [object Object]`

How to actually convert the Drizzle component output into a number or parse the value from the BigNumber and store it within a number? 

I guess it would be possible to .then()nify the conversion into the function itself, but can't find a source to read on how to interact with the web3js behind the Drizzle components.

**Comment by DiscRisknBisque** [comment]
Thanks for bringing this to our attention @rrubo! I'm closing this for now because of its age, but please reopen if this is still an issue.

For reference, you can access the instance of web3 instantiated by Drizzle with `drizzle.web3`.
