### ISSUE TITLE
Log Saga Error Events.

### ISSUE THREAD

**Issue by soundyogi** [ConsenSys-archive/drizzle-legacy#143]
We really need to log out Saga errors!

For example. I used infura mainnet provider instead of kovan, thats why events were not working for me.

After Inspecting the saga-action-flow I discovered a websocket connection error.

Which led me to the fix (using the correct infura fallback provider)

I am not sure but I think there was a Ticket like this before?

**Comment by DiscRisknBisque** [comment]
@soundyogi We're modularizing the instantiation of web3 and will ensure this error can be captured by the application layer.

**Comment by soundyogi** [comment]
wohooo!
