### ISSUE TITLE
Add a 'retry initialization' option

### ISSUE THREAD

**Issue by cliffhall** [ConsenSys-archive/drizzle-legacy#146]
If I load my DApp while Metamask is logged out, I can detect and display a message that says you need to connect an Ethereum account using Metamask or similar. 

Now, if the I realize I'm just not logged in on Metamask and I go ahead and do so, Drizzle does not recognize this (I can inspect drizzleState and see there are still no accounts).

What I would like is to display a 'Retry Connection' button that the user can press once they've logged in rather than having to refresh the page. That would tell Drizzle to replay its initialization saga, setting initialized to false until the accounts are collected.

**Comment by DiscRisknBisque** [comment]
I believe MetaMask will handle the page refresh now, but going to investigate.

**Comment by DiscRisknBisque** [comment]
Potentially related to #76

**Comment by DiscRisknBisque** [comment]
@cliffhall Thanks for bringing this up. Given your setup, how would you like us to implement this?

**Comment by cliffhall** [comment]
I can’t speak to the implementation much but as I said above, I would like to display a 'Retry Connection' button that the user can press once they've logged into MetaMask, rather than having to refresh the page.

**Comment by cliffhall** [comment]
@DiscRiskandBisque Really, so since I wasn't able to specify the exact implementation for this fix that's obviously needed, you're going to close the bug? If you re-open it, I'll look at it and try to fix it myself.

**Comment by adrianmcli** [comment]
The issue was marked as stale last week by the stalebot, no human closed this issue. We definitely welcome any PRs or discussions for feature additions.
