### ISSUE TITLE
Replace getWeb3 w/ Drizzle-Utils' get-web3

### ISSUE THREAD

**Issue by adrianmcli** [ConsenSys-archive/drizzle-legacy#150]
Take a look at this file: https://github.com/trufflesuite/drizzle/blob/master/src/web3/web3Saga.js

This is how Drizzle current retrieves the Web3 object. Look into using Drizzle-Utils instead: https://github.com/trufflesuite/drizzle-utils/tree/master/packages/get-web3

As of the time of this writing, Drizzle-Utils has not been published to NPM yet. Ping @adrianmcli to do it if he hasn't already.

**Comment by adrianmcli** [comment]
@cds-amal It's been published! You can just run `npm install @drizzle-utils/get-web3`.

**Comment by cds-amal** [comment]
Started work on this on this [feature/utils-web3 branch](https://github.com/trufflesuite/drizzle/tree/feature/utils-web3). Here's [spot testing with drizzle-box](https://youtu.be/D53ME-qEk7g). Note: the console errors occur when switching accounts.

Before closing this, there are some outstanding investigations relating to:
- [ ] Error handling/notification
- [ ] MM `window.ethereum.enable` security access
- [ ] Responsibility/concerns between `@drizzle-utils/get-web3` and `drizzle` 
- [ ] Testing

**Comment by adrianmcli** [comment]
> errors occur when switching accounts

This is handled by subscribing to `@drizzle-utils/current-accounts-stream`

> `window.ethereum.enable`

This is handled by `@drizzle-utils/get-accounts`.

> Responsibility/concerns between `@drizzle-utils/get-web3` and `drizzle`

This is an issue, yes.

---

I'm beginning to think maybe we should hold off on all of this and make the big move to a monorepo first.
