### ISSUE TITLE
Handling events

### ISSUE THREAD

**Issue by julien51** [ConsenSys-archive/drizzle-legacy#16]
Thanks for writing Drizzle!
I am working on a dapp which uses it but I think I need clarification on how to listen to the contract's events. Our dapp is using drizzle-react and we have a `mapStateToProps`. I see that the `events` array for the contract is being updated in the `state` passed to `mapStateToProps` but I am not sure this is what the dapp should use to trigger actions.

Any clarification would be more than welcome! Thanks!

**Comment by julien51** [comment]
Closing as I now understand better how this works. I should have learned more from Redux's approach first!

**Comment by athenawisdoms** [comment]
@julien51 Can you please share what you found? An example code will help many of us. Thanks!

**Comment by soundyogi** [comment]
+1

**Comment by crazyrabbitLTC** [comment]
> @julien51 Can you please share what you found? An example code will help many of us. Thanks!

I'm kinda wondering if anyone at all knows how to use Events with Drizzle, google turns up very little....

**Comment by fbalwy** [comment]
+1
