### ISSUE TITLE
Cannot read property 'transactions' of null

### ISSUE THREAD

**Issue by felipecespedes** [ConsenSys-archive/drizzle-legacy#162]
I'm trying to use drizzle and Infura-Rinkeby but I'm getting the following error: `Cannot read property 'transactions' of null`

I'm not using Metamask/Mist and the code looks like:

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import * as serviceWorker from './serviceWorker';
import Web3  from 'web3';
import { Drizzle } from 'drizzle';
import { DrizzleContext } from 'drizzle-react';

const wsURL = 'wss://rinkeby.infura.io/ws';
const web3 = new Web3(new Web3.providers.WebsocketProvider(wsURL));

const options = {
  contracts: [
    {
      contractName: 'MyContract',
      web3Contract: new web3.eth.Contract(contract.abi, '0x...<contract address>')
    }
  ],
  web3: {
    fallback: {
      type: 'ws',
      url: wsURL
    }
  }
};

const drizzle = new Drizzle(options);

ReactDOM.render(
  <DrizzleContext.Provider drizzle={drizzle}>
    <App/>
  </DrizzleContext.Provider>,
  document.getElementById('root')
);
```

![image](https://user-images.githubusercontent.com/11846311/51044567-6f1a1e00-158f-11e9-9d2f-522f06608776.png)

any ideas about this error?

**Comment by DiscRisknBisque** [comment]
Hi @felipecespedes, can we see a link to your full project to help reproduce? One possible issue could be the Infura endpoint URL. For a while, when Infura was testing websockets, a version or project ID were not required, though now they are. [Here's a link to the relevant documentation](https://infura.io/docs/ethereum/wss/introduction).

**Comment by felipecespedes** [comment]
@DiscRiskandBisque This is a testing repo where this error is happening https://github.com/felipecespedes/drizzle-error-infura
After few seconds you will start getting the error.
![image](https://user-images.githubusercontent.com/11846311/51051136-e3a98880-15a0-11e9-8763-ea196b8f0b54.png)

If you have Metamask installed the error doesn't happen but the idea is to use the dapp without Metamask (at least to see data from the contract).

BTW I have set the infura project ID and still getting the same error.

**Comment by DiscRisknBisque** [comment]
Potentially related to #186.

**Comment by n1c01a5** [comment]
I have also this error. I tried to update web3 to the beta 53 version but it does not fix this issue.
