### ISSUE TITLE
Make available cached web3.eth functions, like getBlockNumber

### ISSUE THREAD

**Issue by Garoth** [ConsenSys-archive/drizzle-legacy#166]
As far as I can tell, there is no way to get Drizzle's internal current block number. In general, there's no system in Drizzle for caching web3.eth functions -- only direct contract calls. As a result, my app would call the regular getBlockNumber constantly. Turns out half my app's eth data usage is this getBlockNumber call

It's simple enough for me to implement a cache myself, but this would ideally be part of Drizzle

**Comment by DiscRisknBisque** [comment]
To clarify, are we talking about a current block number in the store, or a historical cache of blocks from the time of initialization?

**Comment by Garoth** [comment]
I guess having access to a cache of recently seen blocks would be useful. Basically, my thinking is that the client already has this data in drizzle, it's just inaccessible

But in particular, knowing the latest block + block number would be broadly useful imo

Other "global" functions of this type may be useful for more niche situations (ex. getGasPrice), but are less important overall, I think

**Comment by DiscRisknBisque** [comment]
Fixed by PR #170.
