### ISSUE TITLE
MetaMask Stopped Calling Listeners

### ISSUE THREAD

**Issue by epiqueras** [ConsenSys-archive/drizzle-legacy#169]
Has anyone else noticed this? All transactions get stuck on `"pending"`.

I debugged down to the `createTxChannel` function and everything after `.on('transactionHash')` is not being called, even though the transaction is still mined and everything.

This is using MetaMask's provider on Kovan. It was working fine before today.

**Comment by dangell7** [comment]
Can Confirm. Nothing after the hash is called.

**Comment by dangell7** [comment]
You need to update web3 I believe. But this was interesting considering I have 4 contracts now that are not connected to my app. Makes me think I need to implement a different solution to handle transactions.

**Comment by epiqueras** [comment]
But `drizzle` imports web3 internally, that means we need a new release? I wonder what caused this.

**Comment by dangell7** [comment]
A new release? I checked the package and they are using the beta 1.0 which means that they need to keep up with updates or revert to a stable build. Who is in charge of this repo? I can make a PR, but really just `npm install web3` lol @cds-amal If you're not willing to keep up then I will update my fork and direct people there until 1.0 becomes stable? Thoughts?

**Comment by epiqueras** [comment]
I tracked it down. It's a MetaMask issue. Closing this, and opening there.
https://github.com/MetaMask/metamask-extension/issues/6081

**Comment by dangell7** [comment]
It’s actially a web3 issue as you can see they handled it in the last update beta 41. If I remove drizzle, my app works fine. If I update drizzle to 41, drizzle crashes. Though, the update to 41 could be a meta mask issue with drizzle but I doubt it. If I remove drizzle all works just fine.
