### ISSUE TITLE
drizzle object not getting populated post upgrade to React 16.8.1, drizzle 1.3.3

### ISSUE THREAD

**Issue by kombos** [ConsenSys-archive/drizzle-legacy#180]
i upgraded to the following: 
react 16.8.1,
drizzle 1.3.3,
web3 1.0.0-beta.43 (breaking in 1.0.0-beta.37 also)

following this, the drizzle object is not getting populated when the following code is used in index.js : 
`const drizzle = new Drizzle(drizzleOptions, drizzleStore);`

both the drizzleOptions and drizzleStore seems to be getting populated properly. the outputted drizzle object is showing 'ContractList' length as 0, also, 'Contract' property and 'web3' property inside drizzle object are both empty. Any help would be greatly appreciated.

**Comment by DiscRisknBisque** [comment]
Hi @kombos, version 1.3.3 should be pinned at `beta.35`--have you tried using `beta.35` and what were the results? There are known issues related to `web3` integration, which may be affecting you.
