### ISSUE TITLE
currentBlock is empty

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [ConsenSys-archive/drizzle-legacy#181]
currentBlock in state is an empty object

**Comment by DiscRisknBisque** [comment]
Are you by chance using `ganache-cli` with automine? `currentBlock` is filled on new blocks, so if automine is enabled, `currentBlock` will not populate until something causes a block to be mined.

This brings up a good enhancement though: we should fetch the initial current block on initialization.

**Comment by Xuefeng-Zhu** [comment]
yes, I am using ganache-cli. I wonder if there is a way to go around it? Should I disable the auto mine?

**Comment by cds-amal** [comment]
Hi @Xuefeng-Zhu you can start up ganache-cli with the `--blockTime` flag, specifying the seconds you want to use. For example `ganache-cli --blockTime 3` to specify 3 seconds. The command is documented in the command line help: `ganache-cli --help`
