### ISSUE TITLE
Saga effects without a yield leads to incorrect logic

### ISSUE THREAD

**Issue by rawfalafel** [ConsenSys-archive/drizzle-legacy#189]
Code in question is in `contractsSaga.js` [here](https://github.com/trufflesuite/drizzle/blob/8f46c5919eee543e62ef04438c28151ea444a254/src/contracts/contractsSaga.js#L222) and [here](https://github.com/trufflesuite/drizzle/blob/8f46c5919eee543e62ef04438c28151ea444a254/src/contracts/contractsSaga.js#L280). 

Should these have a `yield` in front? The call is always returning true, leading to bugs when the last parameter is an object.

**Comment by cds-amal** [comment]
Thanks for reporting this @rawfalafel! `call` returns an object which is truthy. Would appreciate a PR if you tackled this already.

**Comment by rawfalafel** [comment]
Cool! I submitted a PR, although they're missing tests.
