### ISSUE TITLE
Drizzle cache does not clear error message

### ISSUE THREAD

**Issue by rawfalafel** [ConsenSys-archive/drizzle-legacy#192]
Steps to reproduce:
1. Call `cacheCall` on a contract method that reverts
2. Wait until `drizzleState` contains error message in cache
3. Update contract state so that the method doesn't revert
4. Let `cacheCall` execute again. This time no revert.

Expected: cache doesn't contain contain error message
Actual: cache contains error message

Here's my fix which also handles the inverse case (clearing `value` when a method suddenly reverts): https://github.com/UMAprotocol/drizzle/commit/4581c3dc22be88bf2b98b79599354ff63cf68bca

**Comment by cds-amal** [comment]
Thanks @rawfalafel! Can you submit a PR?

**Comment by rawfalafel** [comment]
Bump. I opened a PR for this issue that hasn’t been addressed. Thanks :)
