### ISSUE TITLE
Better error message for invalid event name

### ISSUE THREAD

**Issue by rahulmutt** [ConsenSys-archive/drizzle-legacy#199]
It's fairly easy to make typos when specifying events to listen to and a really large stacktrace comes up if you do.

A basic check should be done inside of `addContract` that ensures that the specified event names match up with the contract ABI and throws a readable exception if an invalid event is specified.

Also willing to PR this one if there's no problem.

**Comment by cds-amal** [comment]
Thanks @rahulmutt! Fantastic idea to validate event names. Would love to see a PR
