### ISSUE TITLE
Support providers without subscription support (like MetaMask).

### ISSUE THREAD

**Issue by Pedro-vk** [ConsenSys-archive/drizzle-legacy#20]
Is not possible to use Drizzle using MetaMask, that's because Drizzle uses subscriptions.
`web3.eth.subscribe('newBlockHeaders' /* ... */)`
Is not possible to check the updates asking for the block number? 
I did this to check the updates closer to the real change (using `rxjs`, but can be done simplest):
```typescript
 Observable
    .interval(100)
    .startWith(undefined)
    .mergeMap(() => Observable.fromPromise(web3.eth.getBlockNumber()))
    .distinctUntilChanged()
    .share();
```

Thanks for your work! The project looks amazing!

**Comment by DiscRisknBisque** [comment]
Hi @Pedro-vk! Thank you for the high praise and sorry for not responding to this sooner. As of v1.1 we offer a polling fallback for web3 providers not supporting subscriptions.
