### ISSUE TITLE
Support for meta transactions

### ISSUE THREAD

**Issue by crisgarner** [ConsenSys-archive/drizzle-legacy#216]
Meta transaction allows developers to pay the gas fee for users with no balance, the Burner Wallet is a case of success using meta transactions. Implementing meta transactions with drizzle is complicated.

Decentralized relayers are a solution and hope soon is available for everyone, some links:

https://medium.com/tabookey/how-to-make-your-dapp-gasless-da15d4d3cacd

https://github.com/tabookey/tabookey-gasless

**Comment by adrianmcli** [comment]
Meta transactions are still very new. I think they are an important part of Ethereum's future, but I doubt we have the bandwidth to work on that at this point. However, if you would like to work on a PR for experimentation purposes, I'd love to take a look.

**Comment by crisgarner** [comment]
@adrianmcli I tried to implement it with drizzle a couple of weeks ago. Documentation of taboo key mentions that you just need to update the provider like:

```
tabookey = require( 'tabookey-gassless')
provider = new tabookey.RelayProvider(web3.currentProvider, {} }
web3.setProvider(provider) 
```

I added the new provider as a custom provider in drizzle options and didn't set the new provider. I'll keep experimenting and let you know.
