### ISSUE TITLE
drizzle installation Error

### ISSUE THREAD

**Issue by pl-jay** [ConsenSys-archive/drizzle-legacy#225]
I just followed [tutorial](https://truffleframework.com/tutorials/getting-started-with-drizzle-and-react#full-component-code) from truffle official page, once i tried to install drizzle with `npm install drizzle` it ended up with following errors, 

> scrypt@6.0.3 preinstall E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt
> node-gyp rebuild

E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.2.0/config.h
  The system cannot find the file specified.
  win_delay_load_hook.cc
C:\Users\Pathum\.node-gyp\10.15.1\x64\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x228B18 [E:\Dev\drizzle-react-tutorial\client\node_mod
ules\scrypt\build\copied_files.vcxproj]
  memlimit.c
  keyderivation.c
  pickparams.c
  hash.c
  win_delay_load_hook.cc
  scrypt_wrapper.vcxproj -> E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\Release\\scrypt_wrapper.lib
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Any suggestions ?

**Comment by adrianmcli** [comment]
Seems to be an issue with Scrypt not building properly on your Node version. Can you try running it on the latest v11 Node?

**Comment by pl-jay** [comment]
@adrianmcli okay i'll try.

**Comment by pl-jay** [comment]
node 12 installed and yet installation fails with new error, 

E:\Dev\drizzle-react-tutorial\client\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  addon.cc
  win_delay_load_hook.cc
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\src\addon.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\keccak\build\keccak.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Dev\drizzle-react-tutorial\client\node_modules\keccak
gyp ERR! node -v v12.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pathum\AppData\Roaming\npm-cache\_logs\2019-05-22T13_40_55_134Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

> scrypt@6.0.3 install E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt
> node-gyp rebuild


E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.2.0/config.h
  The system cannot find the file specified.
  win_delay_load_hook.cc
  copied_files.vcxproj -> E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\Release\\copied_files.node
  memlimit.c
  keyderivation.c
  pickparams.c
  hash.c
  win_delay_load_hook.cc
  scrypt_wrapper.vcxproj -> E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\Release\\scrypt_wrapper.lib
  crypto_scrypt.c
  crypto_scrypt_smix.c
  warnp.c
  sha256.c
  insecure_memzero.c
  scryptenc_cpuperf.c
  mman.c
  gettimeofday.c
  win_delay_load_hook.cc
  scrypt_lib.vcxproj -> E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\Release\\scrypt_lib.lib
  scrypt_common.cc
  scrypt_params_async.cc
  scrypt_params_sync.cc
  scrypt_kdf_async.cc
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\src\node-boilerplate\scrypt_common.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\scrypt.vcxproj]
  scrypt_kdf_sync.cc
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\src\node-boilerplate\scrypt_params_sync.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\scrypt.vcxproj]
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\src\node-boilerplate\scrypt_params_async.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\scrypt.vcxproj]
  scrypt_kdf-verify_sync.cc
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\src\node-boilerplate\scrypt_kdf_async.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\scrypt.vcxproj]
  scrypt_kdf-verify_async.cc
  scrypt_hash_sync.cc
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\src\node-boilerplate\scrypt_kdf_sync.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\scrypt.vcxproj]
  scrypt_hash_async.cc
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\src\node-boilerplate\scrypt_kdf-verify_async.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\scrypt.vcxproj]
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\src\node-boilerplate\scrypt_hash_sync.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\scrypt.vcxproj]
  scrypt_node.cc
  win_delay_load_hook.cc
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\src\node-boilerplate\scrypt_kdf-verify_sync.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\scrypt.vcxproj]
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\scrypt_node.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\scrypt.vcxproj]
c:\users\pathum\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file
..\src\node-boilerplate\scrypt_hash_async.cc) [E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt\build\scrypt.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Dev\drizzle-react-tutorial\client\node_modules\scrypt
gyp ERR! node -v v12.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'E:\Dev\drizzle-react-tutorial\client\node_modules\jest-haste-map\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by adrianmcli** [comment]
I think you misread my last comment. I suggested to try Node v11, not v12.

**Comment by pl-jay** [comment]
i thought node 12v do better, it seems i wrong. althoug installation is success. Thanks @adrianmcli
