### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by bergkvist** [ConsenSys-archive/drizzle-legacy#227]
It would be really helpful if drizzle had typescript declarations. 

Not only for people using Typescript/React with Typescript, but it would also improve the experience for anyone developing in VSCode (intellisense).

**Comment by adrianmcli** [comment]
That's a great idea, we would love to see a PR. But do keep in mind that things are still in flux and the library might have some significant changes by the time you submit a PR for this.
