### ISSUE TITLE
Fallback issue with infura ws

### ISSUE THREAD

**Issue by n1c01a5** [ConsenSys-archive/drizzle-legacy#228]
I have some trouble with the drizzle fallback. 

I have this error: 
```
WebSocket connection to 'wss://kovan.infura.io/ws/v3/<project_id>' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
```

Here is my fallback options configuration for `drizzle`:
```
  web3: {
    fallback: {
      type: 'ws',
      url: wss://kovan.infura.io/ws/v3/<project_id>
    }
  }
```

How I can fix this?

**Comment by cds-amal** [comment]
@n1c01a5 This is a shot in the dark, but did you substitute the appropriate value for `<project_id>` according to the [Infura Documentation](https://infura.io/docs/gettingStarted/authentication)? Otherwise I think it's probably the same as #186 .

**Comment by n1c01a5** [comment]
@cds-amal of course I set up the <project_id> (I put this intentionally).
Yes it's the same issue than #186.
