### ISSUE TITLE
Calling cacheCall on a contract method which returns a struct gives an error - Web3 related

### ISSUE THREAD

**Issue by 0xTimepunk** [ConsenSys-archive/drizzle-legacy#229]
Calling cacheCall on a contract method that should return a struct gives the following error:
`Invalid solidity type: tuple
    at ABICoder._requireType (index.js:74)
    at eval (index.js:100)`

Digging a bit, seems the issue is related to Web3 and was fixed in the 1.0.0-beta.36 release, as described in [https://ethereum.stackexchange.com/questions/36229/invalid-solidity-type-tuple](url) and [https://github.com/ethereum/web3.js/issues/1241](url)

Drizzle is using 1.0.0-beta.35.

It would be interesting to update web3 in Drizzle. In the meantime I will have to play a workaround in my solidity code to return parts of the struct.

Thanks

**Comment by cds-amal** [comment]
@j-mars Apologies for the situation you're in. We had to pin to web3 1.0.0-beta.35 because of breaking changes in web3 and we're awaiting a resolution, (which is in the works)
