### ISSUE TITLE
Issues with library build setup

### ISSUE THREAD

**Issue by balasan** [ConsenSys-archive/drizzle-legacy#25]
There are several issues with the build setup at the moment - will open a PR shortly:

- `babel-polyfill` modifies the global namespace, so should be avoided in libraries, this results in an error if used in another project that also uses babel-polyfill: Uncaught Error: only one instance of babel-polyfill is allowed. `babel-plugin-transform-runtime` should be used instead
- webpack is currently adding is adding dependencies to the build file`redux`, `redux-saga`, `web3` - these should be set as 'external'
- `.gitignore` should not exclude dist folder so that the library can be installed via github (testing, using different versions) + without libraries code is 200K

**Comment by DiscRisknBisque** [comment]
Closing because the PR is merged.
