### ISSUE TITLE
Drizzle 1.1.0 failed with project that works 6 days ago with 1.0.1!

### ISSUE THREAD

**Issue by LeeDark** [ConsenSys-archive/drizzle-legacy#32]
First of all drizzle.js (/node_modules/drizzle/drizzle.js) now is minimized and has strange date: 26.10.1985.

My dapp returns this errors in the console:

```
Error initializing Drizzle:
__stack_frame_overlay_proxy_console__ @ index.js:2178
TypeError: Cannot read property 'blocks' of undefined
    at drizzle.js:8
    at _ (drizzle.js:13)
    at Generator._invoke (drizzle.js:13)
    at Generator.t.(:3000/anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:8248:76586)
    at P (drizzle.js:8)
    at Object.y [as cont] (drizzle.js:8)
......
```

I am noob with all these tools and just worked under tutorial:
http://maksimivanov.com/posts/ethereum-react-dapp-tutorial-part-2

**Comment by tarrencev** [comment]
Make sure you are passing "polls" in the drizzle `options` like:

```
const options = {
  contracts: [...],
  events: {
    ...
  },
  polls: {},
}
```

**Comment by abustamam** [comment]
@tarrencev That worked like a charm. This should be added to the docs then.

**Comment by morrigan** [comment]
`polls` but also `events` should be passed!

**Comment by DiscRisknBisque** [comment]
Ahh this is because of poor key checking on the options object, [v1.1.2](https://github.com/trufflesuite/drizzle/releases/tag/1.1.2) fixes this so that in the future you do not HAVE to include `polls`.

@morrigan [v1.1.3](https://github.com/trufflesuite/drizzle/releases/tag/1.1.3) fixes this for the `events` key as well!

**Comment by jamjamlong266** [comment]
@LeeDark is app is running now ?

**Comment by bellaj** [comment]
sometimes you need only to unlock metamask if you use it
