### ISSUE TITLE
Add more configurable event options

### ISSUE THREAD

**Issue by nharlow89** [ConsenSys-archive/drizzle-legacy#39]
Currently subscribing to events via drizzle options is not configurable. It would be great to extend the drizzle event options to match the [web3 Contract.events options](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#contract-events).

The main use-case I have is pulling in events since contract creation and then listening for future events. I understand that this can easily be accomplished using the existing web3 methods (that `DrizzleContract.js` extends) but it would be cleaner if those events can exist in the drizzle state.

**Comment by nharlow89** [comment]
#40

**Comment by soundyogi** [comment]
Hi I think this is merged and the Issue can be closed.

What I am missing though is a simple usage example of configuring the DrizzleStore aswell as getting the event data. it seems to confuse a lot of people.

**Comment by nharlow89** [comment]
@soundyogi I am not sure if this question was directed towards this particular merge or just the package in general. Here is an example of passing event options to the configs:

> Ex: Contract named `Escrow` with an event named `FundsWithdrawn` and `FundsAvailableForWithdraw`.:
> 
> ```js
> contracts: [
>     Escrow
> ],
> events: {
>     Escrow: [
>         'FundsAvailableForWithdraw',  // listen for 'latest' events
>         {
>             eventName: 'FundsWithdrawn',
>             eventOptions: {
>                 fromBlock: 0 // ideally contract creation block, but listen for events from block '0' to 'latest'
>             }
>     ]
> }
> ```

If you need help reading data from the DrizzleStore you might reference [drizzle-react-components](https://github.com/trufflesuite/drizzle-react-components).
