### ISSUE TITLE
Performance interacting directly with the blockchain 

### ISSUE THREAD

**Issue by elie222** [ConsenSys-archive/drizzle-legacy#47]
In the past when writing dapps we've always needed a caching layer in between to speed things up. How would drizzle handle this?

**Comment by soundyogi** [comment]
Do you have concrete performance issues?
I believe drizzle uses a cache system already. Hence the interface ```cacheCall()``` and ```cacheSend()```
Drizzle updates the data with every block.
This can probably be closed?

**Comment by DiscRisknBisque** [comment]
Hi @elie222 , Drizzle essentially acts as a caching layer between the blockchain and your dapp. Closing this for now, but please reach out if you'd like to discuss more: josh@trufflesuite.com.
