### ISSUE TITLE
Usage with uport

### ISSUE THREAD

**Issue by tayzlor** [ConsenSys-archive/drizzle-legacy#54]
Can you use this in conjunction with uport? As uport injects its own web3 instance?

**Comment by eccentricexit** [comment]
@tayzlor did you manage to do it?

**Comment by barlock** [comment]
So far I've determined that no, it's not currently possible. 


The things in the way are:

1. `uport-connect` uses web3 < 1.0. This will change when uport-connect releases v1.0.0.

2. `drizzle` doesn't easily support constom providers, you can pretty easily hack that though.... `window.web3 = { currentProvider: new Provider(...) };`

2. `uport-connect`'s provider seems to be incompatible with drizzle. As best I can tell, drizzle expects either a websocket from ganache or metamask. You would need to get feature parity with probably metamask to make uport work. A uPort dev suggested that maybe using [Metamask's provider engine](https://github.com/MetaMask/provider-engine) and reimplementing their own provider would likely do the trick.

**Comment by DiscRisknBisque** [comment]
@tayzlor @barlock addressed this quite well. We do plan to more easily support custom providers in the future (especially relevant for hardware wallets), but uPort's in particular will need to upgrade to support websockets.

**Comment by barlock** [comment]
Is there an issue to track custom providers?
