### ISSUE TITLE
Errors Reading blocks w/ Metamask 

### ISSUE THREAD

**Issue by chunkzer** [ConsenSys-archive/drizzle-legacy#55]
![image](https://user-images.githubusercontent.com/8446066/39496495-8b1f3b4e-4d53-11e8-8819-f2f24df64577.png)

After a transaction while I wait for confirmation I get a bunch of these errors popping through console (though eventaully the transaction is successful and state is updated)

**Comment by LayneHaber** [comment]
Getting the same error with accounts on rinkeby

**Comment by chunkzer** [comment]
Same error still happening, some blocks randomly turn out to be null: 

![image](https://user-images.githubusercontent.com/8446066/39727591-2f984e46-5208-11e8-9764-786a65a08851.png)

Added reprocessing flow that seems to take care of it on: https://github.com/trufflesuite/drizzle/pull/57

**Comment by DiscRisknBisque** [comment]
Fixed by merging #56 , please re-open if that didn't fix this for your machine.
