### ISSUE TITLE
Install unminified version of drizzle in npm

### ISSUE THREAD

**Issue by leonprou** [ConsenSys-archive/drizzle-legacy#58]
installing `drizzle` through `npm install` gives a minified version. That's a shame, cause I'd prefer to get the sources to debug and understand the workflow better ::sweat_smile:.  Then If I want to, I can minify it myself with `webpack`.

**Comment by yvon** [comment]
I noticed it too.

Here is my approach until it's solved : https://github.com/trufflesuite/drizzle/issues/59#issuecomment-387758476

Install it from GitHub and you'll get the whole sources.

**Comment by DiscRisknBisque** [comment]
@leonprou , we're actively working on this as part of #130--stay tuned! Will keep open until 130's closure.
