### ISSUE TITLE
Bug: Cannot have final argument to solidity call being an Array

### ISSUE THREAD

**Issue by musnit** [ConsenSys-archive/drizzle-legacy#61]
If the final argument of your cacheCall or cacheSend is an array, it doesn't work.

See: https://github.com/trufflesuite/drizzle/blob/71f37bbbbed7f9e8bd5484d4917fb73ce8b5e30d/src/contracts/contractsSaga.js#L92-L102

The check on Line 92, checking for an options hash as the final argument is catching a false positive when an array is the final argument. Not sure about an easy fix for this - the API may need to be changed?

Also, mutating the actual args (line 99 and elsewhere in the file) seems like a bad pattern, rather than keeping them immutable and making a new array to use in the txObject?

**Comment by DiscRisknBisque** [comment]
@musnit Will duplicate this and see what's up. Also, good point on mutation.

**Comment by cds-amal** [comment]
Seems related to #189

**Comment by cds-amal** [comment]
The finalArgs is the optional send or call options for web3 [methods](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id12). 
The `call` saga effect returns an object which is truthy. The fix is to `yield` the result of `call`. Thanks @rawfalafel!
