### ISSUE TITLE
Estimate gas limit

### ISSUE THREAD

**Issue by adambom** [ConsenSys-archive/drizzle-legacy#62]
What's the recommended approach for estimating gas prior to calling `cacheSend`? I'm finding that if I don't set a gas limit, in many cases my transactions are failing with out of gas exceptions.

I'm finding myself needing to do this before every call:

```javascript
let method = contract.methods.methodName;

let gas = await method(...values).estimateGas();

method.cacheSend(...values, { gas });
```

Is there a cleaner pattern for this? Would it make sense to add this to drizzle? I'm using drizzle with drizzle-react and drizzle-react-components for what it's worth, and the `ContractForm` doesn't give you a way to set gas limit from the component props.

**Comment by ProphetDaniel** [comment]
Try to use `drizzle-react-components-plus`, you should then be able to specify gas.
