### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by protolambda** [ConsenSys-archive/drizzle-legacy#67]
It occured to me that there is no license file. Can this be added? The `package.json` uses the default license when creating a new npm package, so that's not very helpful either. Maybe just add a MIT license?

**Comment by gin** [comment]
@DiscRiskandBisque Please close issue.
This issue is fixed recently with https://github.com/trufflesuite/drizzle/pull/83

https://github.com/trufflesuite/drizzle/blob/master/LICENSE.txt

**Comment by soundyogi** [comment]
can be closed.
