### ISSUE TITLE
Question: Can contract state become stale if it depends on another contract's state?

### ISSUE THREAD

**Issue by tsuberim** [ConsenSys-archive/drizzle-legacy#71]
Example:
```
contract A {
  ERC20 token;
  constructor(ERC20 _token) public {
     token = _token;
  }

  function balance() public view{
     return token.balanceOf(address(this));
  }
}
```
Drizzle will only refresh the state of `balance()` when a transaction is sent to the contract, thus it will not change due to changes in the state if the `token` contract (e.g transfer to/from the contract, minting etc...).

Is this correct?

**Comment by tsuberim** [comment]
bump ^

**Comment by kartojal** [comment]
I'm having issues trying to track an ERC20 token balance with drizzle, that is similar to your code. My balanceOf method does not update after interacting with the contract, only if i do a browser refresh it shows the new balance. Will try to set a minimum project to show.

**Comment by kartojal** [comment]
Nevermind. Was hitting a React issue, a modal was blocking the parent to refresh the drizzle context. My solution was to just close the modal after making the erc20 transaction. In this way the balance is reactive, and the ERC20 contract is inherited from OpenZeppelin, so i'm not hitting @dev-matan-tsuberi  issue.

If i keep the modal open too much time, the parent context data can't re-sync after closing the modal  and need to refresh the browser. 

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by soundyogi** [comment]
@tsuberim I am not sure I understand your issue could you elaborate? Drizzle should have the latest data for each block if you tell it to watch method, right?

**Comment by tomw1808** [comment]
I'm kind of hitting the same issue. Take an ERC20 contract A and some other contract B.

Let's say on initialization `A.getBalance(account)` has the right amount, e.g. 4.

Then do a `A.approve(B.address, 4);`, works fine, doesn't update the balance anyways.

Now the crucial part:

Let's say in Contract B there is a function called "startWithdrawal" that calls `A.transferFrom(msg.sender, address(this), 4);` . Calling `B.startWithdrawal()` won't update the balance.

Then in drizzle the balance remains 4 for contract A unless I completely refresh the page or start interacting with contract A again in some way.

Am I doing something wrong? Am I missing something? 2 days passed trying, and I hit a point where I am a bit lost. I am not a specialist in React, so, if someone tells me it _should_ work then I keep searching. But some help would be appreciated.

**Comment by Ezerous** [comment]
(same or relevant issue)

Let's say we have:

**A.sol**
```solidity
pragma solidity >=0.5.4 <0.6.0;

import './B.sol';

contract A {
    B b;

    constructor(address addr) public {
        b = B(addr);
    }

    function fun() public {
        //...
        b.inc();
    }
}
```

**B.sol**
```solidity
pragma solidity >=0.5.4 <0.6.0;

contract B {
    uint foo;

    function inc() public {
        foo++;
     }

    function getFoo() public view returns (uint) {
        return foo;
    }
}
```

**2_deploy_contracts.js**
```javascript
const A = artifacts.require("A");
const B = artifacts.require("B");

module.exports = function(deployer) {
  deployer.deploy(B).then(function() {
    return deployer.deploy(A, B.address);
  });
};
```

It seems that calling `fun()` will update the state of contract A, but the state of contract B will remain stale (i.e. foo / getFoo() will stay the same in state).

**Comment by in19farkt** [comment]
Any ideas? How to update the "A" balance in drizzle store after calling `transferFrom` from "B" contract?

**Comment by cds-amal** [comment]
Sorry for the late response @in19farkt. You can set the [`syncAlways` option to true in drizzleOptions](https://www.truffleframework.com/docs/drizzle/reference/drizzle-options#-code-syncalways-code-boolean-).
