### ISSUE TITLE
missing dependencies 

### ISSUE THREAD

**Issue by tommycp3** [ConsenSys-archive/drizzle-legacy#78]
Using version drizzle: "1.2.0" 

We upgraded the latest truffle box to drizzle 1.2.0 as given version seemed to have an invalid version of drizzle installed, with no state initialisation helper.

We installed the latest version of these to:
- "deepmerge": "^2.1.0",
- "is-plain-object": "^2.0.4"

on our master package.json file and error was fixed.

**Comment by tommycp3** [comment]
related to #77 but drizzle is missing dependencies in addition.

**Comment by JFGHT** [comment]
Related to https://github.com/trufflesuite/drizzle/issues/59 too.

**Comment by DiscRisknBisque** [comment]
This should now be fixed in v1.2.2. You've corrected hit the issue--the dependencies weren't added to the release `pacakge.json` so were not installing unless otherwise present in the project already.
