### ISSUE TITLE
getPastEvents is not a function

### ISSUE THREAD

**Issue by johnmpotter** [ConsenSys-archive/drizzle-legacy#81]
What's the best way to access past events for a given contract event? If I call the getPastEvents method on a specific contract from the drizzle context, it throws an error that it's not a function. 

```
TypeError: this.drizzle.contracts.Contract.getPastEvents is not a function
```

Or maybe there's a "Drizzle way" for accessing past events that i'm not aware of. Thank you!

**Comment by johnmpotter** [comment]
My short-term solution was to fork drizzle and add the raw web3Contract instance to the drizzle contract and just use that when calling getPastEvents. 

https://github.com/johnmpotter/drizzle/commit/0ff09957ccf4108d71c7583ad57436788596a8fe

I believe the reason the function isn't being added to the DrizzleContract instance has to do with Object.assign, but i'm not sure what the solution would be. I'll leave this open incase someone smarter than myself has the answer.

**Comment by kartojal** [comment]
I'm using drizzle and drizzle-react packages, and a way to use getPastEvents is to use the "web3" instance that comes with Drizzle, injecting the contract ABI and the deployed contract address to `new web3.eth.Contract(abi, address, options)`, creating a raw Web3 contract instance, with all the web3 methods.

Some pseudocode example, can be wrapped into a function for reusing it:
```
const web3 = drizzle.web3;
const yourContract = drizzle.contracts.YourContract;
const yourContractWeb3 = new web3.eth.Contract(yourContract.abi, yourContract.address);
const pastEvents = await yourContractWeb3.getPastEvents(
  'eventName or allEvents',
  {
     fromBlock: 0,
     toBlock: 'latest'
  }
);
```
Could try to recreate a Fiddle for a real React example if you want :smile:  Hope it works for you.

**Comment by soundyogi** [comment]
@kartojal answer is correct.

To access `getPastEvents` you need to access a web3 contract instance.

This Issue can be closed.

Related: https://github.com/trufflesuite/drizzle/issues/149

**Comment by DiscRisknBisque** [comment]
@johnmpotter @soundyogi is correct, @kartojal has the right idea.
