### ISSUE TITLE
addContract function errors

### ISSUE THREAD

**Issue by cosmicapotheosis** [ConsenSys-archive/drizzle-legacy#82]
Expected behavior: The contract is added to the drizzle object which is then accessed via context throughout the other components within the project.

Current behavior: The contract is not added to drizzle, and instead error messages show in the console.

With the contract defined as a contractConfig object with a contractName and a web3Contract as listed on the drizzle repo readme, I get the following error:

uncaught at addContract TypeError: Cannot read property 'length' of undefined
    at generateContractInitialState (http://localhost:3000/static/js/bundle.js:46470:30)
    at contractsReducer (http://localhost:3000/static/js/bundle.js:46379:181)
    at combination (http://localhost:3000/static/js/bundle.js:41875:30)
    at dispatch (http://localhost:3000/static/js/bundle.js:41264:23)
    at http://localhost:3000/static/js/bundle.js:51965:23
    at http://localhost:3000/static/js/bundle.js:39050:19
    at http://localhost:3000/static/js/bundle.js:147272:17
    at dispatch (http://localhost:3000/static/js/bundle.js:42030:19)
    at http://localhost:3000/static/js/bundle.js:50095:13
    at http://localhost:3000/static/js/bundle.js:50625:53

The error originates at the getAbi helper function, the var abi is never defined. In printing the instance of web3Contract.options before the addContract function is called everything looks ok.

Steps to reproduce:

Heres the snippet of code from my project, 

var contractConfig = {
          contractName: 'calendar',
          web3Contract: new this.web3.eth.Contract(Calendar.abi, newCalAddr, {from: this.props.accounts[0]});
        };

        var events = ['NewCalendarEventAdded', 'CalendarEventUpdated', 'CalendarEventDeleted'];

        return this.drizzle.addContract({contractConfig, events});

Other info:

Drizzle 1.2.0
I've tried using a truffle artifact instance (instead of an object with a name and web3 contract instance) in addContract and get the same error.

**Comment by bertiespell** [comment]
@cosmicapotheosis How did you solve this? I'm seeing the same thing

**Comment by johnmpotter** [comment]
@bertiespell I believe the current readme is incorrect. You should pass in 'contractConfig' and 'events' as arguments to the function as opposed to putting them within an object.

Try this instead (notice lack of curly brackets): 
```
this.context.drizzle.addContract(contractConfig, events);
```
