### ISSUE TITLE
Unexpected return type

### ISSUE THREAD

**Issue by LoomiDigital** [ConsenSys-archive/drizzle-legacy#89]
I have a method in a contract which returns a uint:

```
    function numberTest() public pure returns(uint) {
        return 10;
    }
```
However when I call the method from my React component it returns as a string.

To the best of my knowledge the returned value should be:

`BigNumber { s: 1, e: 1, c: [ 10 ] }`

Anyone have any idea what the deal is?

Thanks!

**Comment by DiscRisknBisque** [comment]
Hi @LoomiDigital, can we see the client-side code accessing this variable?

**Comment by DiscRisknBisque** [comment]
Closing this for age and because `BigNumber` has been swapped out for `BN` in `web3`. If you're still experiencing this issue, please re-open.
