### ISSUE TITLE
The error  I can not deploy the contract

### ISSUE THREAD

**Issue by hawkroc** [ConsenSys-archive/drizzle-legacy#90]
I follow the guidelines, but it seemed to show this error in console :Error: Contract has not been deployed to the detected network (network/artifact mismatch) 
How can I get the network_id?

**Comment by mnaamani** [comment]
You can get the network id from the web3 instance of drizzle available in the store:

`drizzle.store.getState().web3.networkId`

**Comment by soundyogi** [comment]
is this resolved?

If you did not deploy via truffle your abi-s wont include the address / network and you have to add web3 contract instances manually when creating the store.

**Comment by DiscRisknBisque** [comment]
Closing this for now because of age and since Drizzle doesn't handle contract deployment. @hawkroc, if you're still having this issue please reopen. Thanks!
