### ISSUE TITLE
generateContractsInitialState export should be default

### ISSUE THREAD

**Issue by Calpoog** [ConsenSys-archive/drizzle-legacy#91]
I'm not an expert with Webpack and all of the different ways javascript can import/require modules. But the issue (that other people seem to be having) of `(0 , _drizzle.generateContractsInitialState) is not a function` when doing an `import { generateContractsInitialState } from 'drizzle'` seems to be caused by some recent updates to the way the individual packages are exported from their files in Drizzle.

Not far back, the generateContractsInitialState file was changed from module.exports to an ES6 export keyword. This works in one of the other two files it is imported in (generateStore) because it does a `import { generateContractsInitialState } from './generateContractsInitialState'`

Expecting the function to not be the default export (even though its the only thing in the file and probably should be). The issue is that in drizzle's index.js it is being imported as `import generateContractsInitialState from './generateContractsInitialState'` This is an issue because webpack is now marking the module as __esModule which in turn causes this:
`function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }`
to return the module as-is, where later in index.js's output it tries to do a .default (and it doesn't have one). This causes the index.js to have undefined for the generateContractsInitialState key, and now the recommendation from the docs and from the drizzle truffle box to do this fails (when "using with an existing redux store"):

```
import { generateContractsInitialState } from 'drizzle'

...

const initialState = {
  contracts: generateContractsInitialState(drizzleOptions)
}
```

With the error in the browser console as mentioned above.

I believe the solve is either to change index.js to import the module the way generateStore.js does OR better yet to make it a default export and change generateStore.js to import it the way index.js does.

**Comment by dangell7** [comment]
This is all related to versioning. Use my pr to update!

**Comment by Calpoog** [comment]
Yep, I see your PR unified those couple files as ES6 and how they're imported. Just as a question though, is there any reason that generateStore and generateContractsInitialState are not default exports when they're the only exports in their respective files? I'm not sure of that's a convention or something.

**Comment by dangell7** [comment]
I'm not really sure, I just started coding a year ago... I do find the way drizzle is structured quite interesting. 

@DiscRiskandBisque can you elaborate?

**Comment by mnaamani** [comment]
see #95

**Comment by DiscRisknBisque** [comment]
Closing because #88 fixed this issue. Thank you @dangell7 !
