### ISSUE TITLE
Missing guidelines for how to contribute

### ISSUE THREAD

**Issue by mnaamani** [ConsenSys-archive/drizzle-legacy#96]
Perhaps we should add a CONTRIBUTING file, or add a section in the README about how to contribute? It should cover:

- To which branch to submit PRs
- Wether PR should include the dist/drizzle.js build file in the PR or not
- Wether PR should include updates to package-lock.json in addition to package.json when updating npm module dependencies

**Comment by DiscRisknBisque** [comment]
@mnaamani Very much agree--with the fixes in 1.2.2 out the door this is the next order of business!

**Comment by DiscRisknBisque** [comment]
@mnaamani Guide is added! [Here's a direct link for convenience](https://github.com/trufflesuite/drizzle/blob/master/CONTRIBUTING.md). If there's more you'd like added, things you'd like clarified or expanded, etc. please let us know.
