### ISSUE TITLE
Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by DalderupMaurice** [ConsenSys-archive/drizzle-legacy#98]
Using ganache-cli version `6.1.5` (with command `ganache-cli -b 3`)
And drizzle options
```
import myContract from "./contract/build/contracts/myContract.json"

const options = {
  contracts: [
    myContract
  ],
  events: {
    myContract: ['Transfer']
  },
  web3: {
    block: false,
    fallback: {
      type: 'ws',
      url: 'ws://127.0.0.1:8545'
    }
  },
  polls: {
    accounts: 1500
  }
};
```

I get the following error message:
```
No web3 instance injected, using fallback.
HomePage.jsx:129 uncaught at root at root 
 at contractsSaga 
 at takeEvery 
 at addContract 
 at instantiateContract 
 TypeError: Cannot read property 'address' of undefined
```
Any clue what's wrong? I am not able to trace the problem

**Comment by DalderupMaurice** [comment]
I didn't realize this problem actually points out that your SC is not deployed 😄

**Comment by Crelde** [comment]
I am having that same issue, how did you resolve..

```
index.js:2178 uncaught at root at root 
 at contractsSaga 
 at takeEvery 
 at addContract 
 at instantiateContract 
 TypeError: Cannot read property 'address' of undefined
    at instantiateContract$ (http://localhost:3000/static/js/bundle.js:103397:107)
    at tryCatch (http://localhost:3000/static/js/bundle.js:101434:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/bundle.js:101668:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:101486:21)
    at next (http://localhost:3000/static/js/bundle.js:160559:27)
    at currCb (http://localhost:3000/static/js/bundle.js:160636:7)
    at runSelectEffect (http://localhost:3000/static/js/bundle.js:160947:7)
    at runEffect (http://localhost:3000/static/js/bundle.js:160683:1212)
    at next (http://localhost:3000/static/js/bundle.js:160563:9)
    at proc (http://localhost:3000/static/js/bundle.js:160518:3)
    at resolveIterator (http://localhost:3000/static/js/bundle.js:160704:5)
    at runCallEffect (http://localhost:3000/static/js/bundle.js:160765:180)
    at runEffect (http://localhost:3000/static/js/bundle.js:160683:648)
    at next (http://localhost:3000/static/js/bundle.js:160563:9)
    at currCb (http://localhost:3000/static/js/bundle.js:160636:7)
    at http://localhost:3000/static/js/bundle.js:160747:16
    at exec (http://localhost:3000/static/js/bundle.js:161377:5)
    at flush (http://localhost:3000/static/js/bundle.js:161418:5)
    at asap (http://localhost:3000/static/js/bundle.js:161391:5)
    at runPutEffect (http://localhost:3000/static/js/bundle.js:160734:69)
    at runEffect (http://localhost:3000/static/js/bundle.js:160683:307)
    at next (http://localhost:3000/static/js/bundle.js:160563:9)
    at currCb (http://localhost:3000/static/js/bundle.js:160636:7)

```

**Comment by DalderupMaurice** [comment]
You have to deploy your Smart Contract and set the address of the Smart Contract using this: https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#options-address @Crelde

**Comment by adrianmcli** [comment]
Adding the following in

**Comment by adrianmcli** [comment]
Make sure to remember to add the following in your `truffle.js` or `truffle-config.js`:

```js
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*" // Match any network id
    }
  }
};
```

It needs to know how to connect to ganache.

**Comment by Bowfish** [comment]
My DApp is working with dirizzle connected to ganache. Now I deployed my contracts to the Rinkeby testnet. How do I have to set up the options that drizzle uses the contracts which are deployed on Rinkeby?

**Comment by adrianmcli** [comment]
@Bowfish See this part of the documentation: https://truffleframework.com/docs/truffle/advanced/networks-and-app-deployment#build-artifacts

But in short, you should be able to use the same `.json` build artifacts, as long as you deployed using Truffle.

**Comment by liberuum** [comment]
Hey @DalderupMaurice , where do you set the contract address exactly? (where in the codebase) I have the same issue as @Crelde . 

. I have followed the [drizzle tutorial](https://truffleframework.com/tutorials/getting-started-with-drizzle-and-react#install-drizzle) to the line and i get this errror.

**Comment by Bowfish** [comment]
@pcatana I set the address in the drizzle options. like this:

```javascript
import MyContract from '../eth/build/contracts/MyContract.json'

const drizzleOptions = {
  web3: {
    block: false,
    fallback: {
      type: 'ws',
      url: 'ws://127.0.0.1:8545'
    }
  },
  // Rinkeby
  contracts: [
   {
      contractName: 'MyContract',
      web3Contract: new web3.eth.Contract(
        MyContract.abi,
        '0x......<contractAddress>',
        {data: 'deployedBytecode' }
      ) // An instance of a Web3 contract
    }
  ],
  /*
  events: {
    SimpleStorage: ['StorageSet']
  },
  */
  polls: {
    //accounts: 1500
  }
}
```

**Comment by adrianmcli** [comment]
@pcatana When you migrate your smart contracts using Truffle, the addresses of the smart contracts are written into the `.json` build artifacts. This is why Drizzle only requires you to pass in the `.json` build artifact file and it should be able to connect to the contract instance automatically.

**Comment by Bowfish** [comment]
@adrianmcli That is pretty cool. In this case, I can delete all the contract stuff in the drizzle options. Right?

**Comment by adrianmcli** [comment]
@Bowfish it depends if your build artifacts are still in sync from when you migrated.

You can open up the JSON file, look under the `networks` key, then find the key with your network ID (in this case, it should be `4` for RInkeby), and then `address`.

Try it and see if it works, I guess.

**Comment by Bowfish** [comment]
@adrianmcli That looks good, but now I get this Metamsk Error. Do you have any idea what that could be?

![metamask-error-01](https://user-images.githubusercontent.com/27821742/44958909-2ff40600-aee7-11e8-8407-61213a55f4b6.png)

![metamask-error-02](https://user-images.githubusercontent.com/27821742/44958939-a42ea980-aee7-11e8-9fed-8d2132beb579.png)

**Comment by liberuum** [comment]
I'm having the contracts imported from the build/ folder. Migrated through truffle, the artifacts work. But somehow it can't read the address somewhere....     
This is my `index.js`:     
```javascript
import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./App";
import registerServiceWorker from "./registerServiceWorker";

// import drizzle functions and contract artifact
import { Drizzle, generateStore } from "drizzle";
import MyStringStore from "./contracts/MyStringStore.json";

// let drizzle know what contracts we want
const options = { 
    contracts: [MyStringStore]
};

// setup the drizzle store and drizzle
const drizzleStore = generateStore(options);
const drizzle = new Drizzle(options, drizzleStore);

// pass in the drizzle instance
ReactDOM.render(<App drizzle={drizzle} />, document.getElementById("root"));
registerServiceWorker();
```

**Comment by adrianmcli** [comment]
@pcatana what specific error do you get?

**Comment by liberuum** [comment]
I get this error
```
index.js:2178 uncaught at root at root 
 at contractsSaga 
 at takeEvery 
 at addContract 
 at instantiateContract 
 TypeError: Cannot read property 'address' of undefined
    at instantiateContract$ (http://localhost:3000/static/js/bundle.js:24074:107)
    at tryCatch (http://localhost:3000/static/js/bundle.js:22059:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/bundle.js:22293:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:22111:21)
    at next (http://localhost:3000/static/js/bundle.js:79613:27)
    at currCb (http://localhost:3000/static/js/bundle.js:79690:7)
    at runSelectEffect (http://localhost:3000/static/js/bundle.js:80001:7)
    at runEffect (http://localhost:3000/static/js/bundle.js:79737:1212)
    at next (http://localhost:3000/static/js/bundle.js:79617:9)
    at proc (http://localhost:3000/static/js/bundle.js:79572:3)
    at resolveIterator (http://localhost:3000/static/js/bundle.js:79758:5)
    at runCallEffect (http://localhost:3000/static/js/bundle.js:79819:180)
    at runEffect (http://localhost:3000/static/js/bundle.js:79737:648)
    at next (http://localhost:3000/static/js/bundle.js:79617:9)
    at currCb (http://localhost:3000/static/js/bundle.js:79690:7)
    at http://localhost:3000/static/js/bundle.js:79801:16
    at exec (http://localhost:3000/static/js/bundle.js:80431:5)
    at flush (http://localhost:3000/static/js/bundle.js:80472:5)
    at asap (http://localhost:3000/static/js/bundle.js:80445:5)
    at runPutEffect (http://localhost:3000/static/js/bundle.js:79788:69)
    at runEffect (http://localhost:3000/static/js/bundle.js:79737:307)
    at next (http://localhost:3000/static/js/bundle.js:79617:9)
    at currCb (http://localhost:3000/static/js/bundle.js:79690:7)
```

**Comment by adrianmcli** [comment]
@pcatana that's weird, have you tried restarting `ganache` and then running `truffle migrate --reset`? You can also feel free to delete the `build` folder before this, just in case.

That'll rebuild your build artifacts from scratch and hopefully it'll be able to find the address and connect to your contract.

**Comment by liberuum** [comment]
Just did. The error still persists...    
I get this weird network id in the contract artifact.      
Don't know if it's of any relevance. 
![image](https://user-images.githubusercontent.com/19393057/44959361-4309d480-aeed-11e8-8b4e-8f66e4a0d842.png)

I am running the Drizzle tutorial, and I am trying to deploy the contracts on the ganache-cli b 3. Somewhere, drizzle is not reading the contract?

**Comment by adrianmcli** [comment]
@pcatana Did you specify your network in `truffle.js` and `truffle-config.js` as described in this section: https://www.truffleframework.com/tutorials/getting-started-with-drizzle-and-react#specify-the-network

**Comment by liberuum** [comment]
Yes I do:

```
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*" 
    }
  }
};
```

**Comment by liberuum** [comment]
I have the tutorial here: https://github.com/pcatana/truffle-drizzle-tutorial in case you want to try it.

**Comment by adrianmcli** [comment]
@pcatana I just tried it and it worked perfectly fine for me. Maybe you have MetaMask installed and is connected to the main network? For initial development, I always recommend people to use an incognito window without MetaMask so you don't run into this problem.

Consider this section: https://www.truffleframework.com/tutorials/getting-started-with-drizzle-and-react#wire-up-the-react-app-with-drizzle

**Comment by liberuum** [comment]
Damn. It works. You're right. Thank you @adrianmcli

**Comment by adrianmcli** [comment]
@pcatana This is actually a pretty common mistake. I think maybe I should bold that point or something. Thanks for letting us know actually, it's something we need to bring more attention to.

**Comment by liberuum** [comment]
@adrianmcli that's a good idea.

**Comment by znss1989** [comment]
@adrianmcli I am having the same problem as with pcatana when trying on the Drizzle tutorial, but alrady running the tutorial application in incognito window in Chrome canary. 

![image](https://user-images.githubusercontent.com/9821703/45139892-d8ee7980-b1e3-11e8-8bc5-913212d0fb04.png)

The current state of code can also be found here https://github.com/znss1989/drizzle-react-tutorial. Spent quite a few hours to figure out the causes, with no luck. 

My `index.js` and `App.js` files are as below:
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { Drizzle, generateStore } from 'drizzle';

import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import MyStringStore from './contracts/MyStringStore.json';

// let drizzle know what contracts we want
const options = { contracts: [MyStringStore] };

// setup the drizzle store and drizzle
const drizzleStore = generateStore(options);
const drizzle = new Drizzle(options, drizzleStore);

// pass in the drizzle instance
ReactDOM.render(<App drizzle={drizzle} />, document.getElementById("root"));
registerServiceWorker();
```

```javascript
import React, { Component } from 'react';

import logo from './logo.svg';
import './App.css';

class App extends Component {
  state = {
    loading: true,
    drizzleState: null
  };

  componentDidMount() {
    const { drizzle } = this.props;
    // subscribe to changes in the store
    this.unsubscribe = drizzle.store.subscribe(() => {
      // every time the store updates, grab the state from drizzle
      const drizzleState = drizzle.store.getState();
      // check to see if it's ready, if so, update local component state
      if (drizzleState.drizzleStatus.initialized) {
        this.setState({ loading: false, drizzleState });
      }
    });
  }

  componentWillUnmount() {
    this.unsubscribe();
  }

  render() {
    if (this.state.loading) return "Loading Drizzle...";
    return <div className="App">Drizzle is ready</div>;
  }
}

export default App;
```

**Comment by adrianmcli** [comment]
@znss1989 I see your problem. You're not making a symlink as per this [section](https://www.truffleframework.com/tutorials/getting-started-with-drizzle-and-react#link-up-our-build-artifacts). Rather, you're just copying the JSON build artifact files over from `build` to `src`. Drizzle looks into the JSON build artifacts to find out what address your contracts were deployed at, so it always needs the most updated ones after a migration.

I've cloned your repo and have tested that putting in a proper symlink fixes it.

**Comment by znss1989** [comment]
@adrianmcli Thanks for spending time to help me figuring out the possible cause there. Actually, I followed the steps to use symlink by `ln -s ../../build/contracts contracts`, but I did so in git bash on a Windows 10 machine. Is that a problem? Is the command executed differently in Windows? 

Or only should I use `mklink \D contracts ..\..\build\contracts` in command prompt as mentioned?

**Comment by adrianmcli** [comment]
@znss1989 I haven't used git bash on Windows to make a symlink myself, so maybe there are some quirks with it. I found this StackOverflow [question](https://stackoverflow.com/questions/18641864/git-bash-shell-fails-to-create-symbolic-links) though, but I am not sure if it helps your situation. If all else fails, using `mklink` should work in a normal `cmd` shell (I think?).

**Comment by liberuum** [comment]
I've tried to use `mklink` on windows but couldn't. So, I used the [linux subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) on windows with the `ln` command.

**Comment by adrianmcli** [comment]
Btw, I know this symlink business is really annoying. We hope to have a fix for this in Truffle v5.1 so that you can simply define a path for where to dump your build artifacts. Windows support is one of the most challenging things I've had to deal with.

**Comment by DalderupMaurice** [comment]
My previous comment https://github.com/trufflesuite/drizzle/issues/98#issuecomment-410180793 should help you. You should place this code right after initializing your contract in web3
Like this:
```
import contractJSON from "../contract/build/contracts/mycontract.json";

const web3 = new Web3(Web3.givenProvider || "ws://localhost:8545");
const contract = new web3.eth.Contract(contractJSON.abi);
contract.options.address = "<place your contract address from deployment here>"; // ex: 0x3078d436637e5ba92aac2bc32436709c9692a4d1
```
@pcatana @adrianmcli 

To avoid having to copy the built JSON the whole time, I have a folder `contract` with my contract/truffle project in it. When I build it, I point to `contract/build/contracts/xxx.json` as seen in the example. No need for symlinks.

Also, you DO have the option to choose your build path.
```
{
  compilers: {
    external: {
      command: "./compile-contracts",
      targets: [{
        path: "./path/to/artifacts/*.json"
      }]
    }
  }
}
```

As seen here: https://github.com/trufflesuite/truffle/releases CTRL+F `Target generated artifacts`

**Comment by adrianmcli** [comment]
@DalderupMaurice The problem with directly importing from the `build/contracts` folder is that you are not allowed to import files outside of in Create-React-App unless you eject. That's really the only reason for the symlink. But by all means, you don't need to use Create-React-App at all either. It's just used for simple illustration.

**Comment by DalderupMaurice** [comment]
That's what I am saying. Having the `contracts` map with my truffle project INSIDE the react app allows you to import it

**Comment by adrianmcli** [comment]
Having an entire Truffle project inside the `src` folder of a Create-React-App is maybe even more awkward than the symlink approach or even ejecting. I want to say that you can do it if all you need to do is just to make it run, but I can't help but feel like you are better off with the other approaches.

**Comment by DalderupMaurice** [comment]
Well, In my case it was just 1 file from my contract, 1 config file and my build folder, which is my `whole truffle project`, no harm done there :P 
I have truffle-cli installed globally and use that to deploy/compile

**Comment by RicoRicoCA** [comment]
I had the same error as pcatana and znss1989: 
"index.js:2178 uncaught at root at root 
 at contractsSaga 
 at takeEvery 
 at addContract 
 at instantiateContract 
 TypeError: Cannot read property 'address' of undefined..."

and fixed it by using "truffle console" to launch truffle,
and then using "compile" and "migrate --reset" from within. 

Whereas i had been using "truffle develop" (ie not console), which sets up its own addresses blockchain etc. and has the effect of deploying the contract to the 'wrong' blockchain, which is why we see 'address' of undefined
Console, by contrast, connects to the ganache cli that is already running, which is what we want.
So if you were using 'develop' give the above a try.

Also note that if using windows, when you set up the symlink you must invoke the cli with 'run as administrator' and the correct syntax is:
mklink /D contracts ..\build\contracts
(whereas the tutorial uses the 'wrong' slash for '/D')

I hope this info is helpful to somebody.

**Comment by palexs** [comment]
In my case MetaMask was active and pointed to Rinkeby Test Network. I had to switch it to Localhost 8545.
